<?php

namespace models\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StudentInscribeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentInscribeRepository extends EntityRepository
{
}
